# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_auto_20170612_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='projects',
            field=models.ManyToManyField(to='partners.Project'),
        ),
    ]
